# Generated by Django 4.2.4 on 2023-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_progress', 'In_progress'), ('Done', 'Done'), ('Canceled', 'Canceled')], default=1, max_length=12),
        ),
    ]
