# Generated by Django 4.2.4 on 2023-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='description_user',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
