# Generated by Django 4.2.4 on 2023-09-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='img/default.jpg', upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
