# Generated by Django 4.2.4 on 2023-09-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='img/default.jpeg', upload_to='img/'),
        ),
    ]
