# Generated by Django 4.2.4 on 2023-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='created_at',
        ),
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'in_progress'), (3, 'done'), (4, 'canceled')], default=1),
            preserve_default=False,
        ),
    ]
