# Generated by Django 4.2.4 on 2023-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_requests_created_at_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.TextField(choices=[('pending', 'pending'), ('2', 'in_progress'), ('3', 'done'), ('4', 'canceled')], default=1),
        ),
    ]
