# Generated by Django 4.2.4 on 2023-09-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_remove_dessert_publish_date_dessert_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='dessert',
            name='instructions',
            field=models.TextField(default='test'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In Progress', 'In Progress'), ('Canceled', 'Canceled')], default='In Progress', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.dessert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
