# Generated by Django 4.2.4 on 2023-09-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Confirm',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
