# Generated by Django 4.2.4 on 2023-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='problem_discription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
