# Generated by Django 4.2.4 on 2023-09-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_problem_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='problem_discription',
            new_name='pro_discription',
        ),
    ]
