# Generated by Django 4.2.4 on 2023-09-03 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_problem_discription_servicerequest_pro_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
