# Generated by Django 4.2.4 on 2023-09-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
