# Generated by Django 4.2.4 on 2023-09-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_childrenshirt_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_shirt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.childrenshirt'),
            preserve_default=False,
        ),
    ]
