# Generated by Django 4.2.4 on 2023-09-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_child_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='child_shirt',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.childrenshirt'),
            preserve_default=False,
        ),
    ]
