# Generated by Django 4.2.4 on 2023-09-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_child_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='child_shirt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.childrenshirt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shirt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shirt'),
        ),
    ]
