# Generated by Django 4.2.4 on 2023-09-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicerequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
