# Generated by Django 4.2.4 on 2023-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_servicerequest_status_alter_service_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.TextField(choices=[('pending', 'pending'), ('in_progres', 'in_progres'), ('Done', 'Done'), ('canceled', 'canceled')], default='pending'),
        ),
    ]
