# Generated by Django 4.2.4 on 2023-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_servicerequest_deadline_servicerequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.TextField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('Done', 'Done'), ('canceled', 'canceled')], default='pending'),
        ),
    ]
