# Generated by Django 4.2.4 on 2023-09-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_service_servicerequest_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pendin'), ('in_progress', 'in_progress'), ('done', 'done'), ('canceled', 'canceled')], default='pending', max_length=120),
        ),
    ]
