# Generated by Django 4.2.4 on 2023-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=2048)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
            ],
        ),
    ]
