# Generated by Django 4.2.4 on 2023-09-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_title_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='note',
            field=models.TextField(default='note'),
        ),
    ]
