# Generated by Django 4.2.4 on 2023-09-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicerequest_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='note',
        ),
    ]
