# Generated by Django 4.2.4 on 2023-09-04 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='request_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
