# Generated by Django 4.2.4 on 2023-09-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_servicerequest_request_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='note',
            field=models.TextField(default='..'),
        ),
    ]
