# Generated by Django 4.2.4 on 2023-09-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=2048),
        ),
    ]
