# Generated by Django 4.2.4 on 2023-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_alter_userrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), (' done', 'done '), ('canceled', 'canceled')], default='Pending', max_length=2048),
        ),
    ]
