# Generated by Django 4.2.4 on 2023-09-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_alter_userrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='description_user',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
